project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from agit_material.views import AgitMaterialListView, AgitMaterialDetailView, SearchView, test

urlpatterns = [
    url(r'^$', SearchView.as_view()),
    url(r'^material/$', AgitMaterialListView.as_view()),
    url(r'^material/(?P<pk>\d+)/$', AgitMaterialDetailView.as_view(), name="material_detail"),

    url(r'^admin/', include(admin.site.urls)),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agit_material/models.py
# -*- coding: utf-8 -*-
from django.core.exceptions import ValidationError
from djangosphinx.models import SphinxSearch

from django.db import models

FORMAT_CHOICES = (
    (1, 'A1'),
    (2, 'A2'),
    (3, 'A3'),
    (4, 'A4'),
    (5, 'A5'),
    (6, 'Буклет'),
)

TYPE_CHOICES = (
    (1, 'плакат'),
    (2, 'листовка'),
    (3, 'растяжка'),
    (4, 'банер'),
)


def file_is_image(file):
    file_name = file.file.name
    ext = file_name.split('.').pop().lower() # extension of file

    if ext not in ['jpg', 'png', 'svg']:
        raise ValidationError(u'%s is not image file. Please upload jpg, png or svg file' % file_name)




class TargetGroup(models.Model):
    title = models.CharField(u'Название', max_length=64)

    def __unicode__(self):
        return self.title



class File(models.Model):
    file = models.FileField(upload_to='agit_materail_files')
    description = models.TextField(u'Описание/Комментарий', blank=True)
    agit_material = models.ForeignKey('AgitMaterial', related_name="files")

    def file_name(self):
        return self.file.file.name.split("/").pop()


class Picture(models.Model):
    agit_material = models.ForeignKey('AgitMaterial', related_name="pictures", null=True, blank=True)

    title = models.CharField(u'Название', max_length=64)
    image = models.FileField(upload_to='pictures', validators=[file_is_image, ])
    tags = models.CharField(u'Теги', max_length=255)
    # width = models.PositiveSmallIntegerField(null=True, blank=True)
    # height = models.PositiveSmallIntegerField(null=True, blank=True)

    search = SphinxSearch(
        index='agit_material_pictures',
        weights={
            'title': 100,
            'tags': 100,
        },
        mode='SPH_MATCH_EXTENDED',
    )

    def __unicode__(self):
        return self.title

    def is_svg(self):
        file_name = self.image.file.name
        ext = file_name.split('.').pop().lower() # extension of file
        return ext == 'svg'


class AgitMaterial(models.Model):
    title = models.CharField(u'Название', max_length=64)
    image = models.FileField(u'Превью', upload_to='agit_materail_previews', validators=[file_is_image, ])
    tags = models.CharField(u'Теги', max_length=255)
    target_group = models.ManyToManyField(TargetGroup, help_text=u'Целевая аудитория')

    format = models.PositiveSmallIntegerField(choices=FORMAT_CHOICES, null=True, blank=True)
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, null=True, blank=True)

    description = models.TextField(u'Описание', blank=True)
    insctruction = models.TextField(u'Инструкция по изготовлению', blank=True)


    search = SphinxSearch(
        index='agit_material_agitmaterial',
        weights={
            'title': 100,
            'tags': 100,
            'groups': 95,
            'description': 90,

        },
        # mode='SPH_MATCH_ALL',
        # http://sphinxsearch.com/docs/latest/matching-modes.html
        # http://sphinxsearch.com/docs/latest/extended-syntax.html
        mode='SPH_MATCH_EXTENDED',
        # rankmode='SPH_RANK_NONE',
        # rankmode='SPH_RANK_MATCHANY', # not work
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['id']

agit_material/forms.py
# -*- coding: utf-8 -*-
from django import forms



class SearchForm(forms.Form):
    text = forms.CharField(label=u'Введите фразу для поиска', max_length=50, required=False)

agit_material/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from  django.views.generic import FormView, ListView, DetailView
from  django.views.generic.edit import FormMixin
# from django.views.decorators.csrf import csrf_exempt

from . forms import SearchForm
from . models import AgitMaterial, Picture


class AgitMaterialListView(ListView):
    queryset = AgitMaterial.objects.all()
    paginate_by = 10

class AgitMaterialDetailView(DetailView):
    model = AgitMaterial






class AgitMaterialSearchMixin(object):
    def agit_search(self, text):
        query = u'@(title,tags,description,groups) %s' % text
        return AgitMaterial.search.query(query)


class PictureSearchMixin(object):
    def picture_search(self, text):
        query = u'@(title,tags) %s' % text
        return Picture.search.query(query)



class SearchView(ListView, AgitMaterialSearchMixin, PictureSearchMixin):
    template_name = 'agit_material/search.html'
    form_class = SearchForm
    paginate_by = 10

    def get(self, request):
        self.form = self.form_class(request.GET)
        self.object_list = self.get_queryset() # for post method
        return super(SearchView, self).get(request)

#    def post(self, request):
#        # self.form = self.get_form(self.form_class)
#        # self.object_list = self.get_queryset()
#        return self.render_to_response(self.get_context_data())

    def get_queryset(self):
        # qs = AgitMaterial.objects.none()
        qs = AgitMaterial.objects.order_by('-id')[:self.paginate_by] # latest

        if self.form.is_valid():
            # Sphinx search
            text = self.form.cleaned_data['text']
            if text:
                qs = self.agit_search(text)
        else:
            print self.form.errors

        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(SearchView, self).get_context_data(*args, **kwargs)
        context['form'] = self.form
        if self.form.is_valid():
            text = self.form.cleaned_data['text']
            if text:
                context['query_string'] = 'text=%s' % text
                context['pictures'] = self.picture_search(text)[0:10]
            else:
                 # just show latest pictures
                context['pictures'] = Picture.objects.order_by('-id')[:self.paginate_by] # latest

        return context


# not used
class SearchViewFormView(FormView):
    template_name = 'agit_material/search.html'
    form_class = SearchForm
    success_url = '/'

    def form_valid(self, form):
        text = form.cleaned_data['text'] # text to search
#       print(text)
#        results = AgitMaterial.search.query(text)
#        print results.count()
#        for a in results:
#            print a.title
        query = u'@(title,tags,description) ' + text
        results = AgitMaterial.search.query(query)

        context = {'form': form, }
        return self.render_to_response(context)
        # return super(SearchView, self).form_valid(form)





def test(request):
    print("test_________")

    #return render_to_response('agit_material/search.html')
    return HttpResponse("TEST!!!!")

agit_material/templates/agit_material/agitmaterial_detail.html
{% extends 'agit_material/base.html' %}


{% block content %}
    <h3>{{object.title }}</h3>
    {{ object.tags }}<br>
    <img src="{{ object.image.url }}" height=250><br>

    Формат: {{ object.get_format_display|default:"---" }}<br>
    Тип: {{ object.get_type_display|default:"---" }}<br>
    Целевая аудитория: {{ object.target_group.all|join:", " }}<br>
    <br><br>

    Описание:<br>
        {{ object.description }}
    <br><br>

    Инструкция:<br>
        {{ object.description }}
    <br><br>

    Файлы:<br>
    {% for f in object.files.all %}
        <a href="{{ f.file.url }}">{{ f.file_name }}</a>
        {{ f.description }}<br>
    {% endfor %}
    <br><br>

    Рисунки:<br>
    {% for p in object.pictures.all %}
        {{ p.title }}<br>
        <a href="{{ p.image.url }}">{{ p.image.url }}</a>
        {{ p.tags }}<br>
    {% endfor %}

{% endblock %}

agit_material/templates/agit_material/agitmaterial_list.html
{% extends 'agit_material/base.html' %}



{% block content %}
    {% include 'agit_material/blocks/_atigmaterial_list.html' %}
{% endblock %}

agit_material/templates/agit_material/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    <div class="content">
        {% block content %}{% endblock %}

    </div>

</body>



</html>

agit_material/templates/agit_material/blocks/_atigmaterial_list.html
<table>
    <thead>
        <tr>
            <th>Заголовок</th>
            <th>Формат</th>
            <th>Тип</th>
            <th>Целевая аудитория</th>
        </tr>
    </thead>
    <tdbody>
    {% for m in object_list %}
        <tr>
            <td><a href="{% url 'material_detail' m.id %}">{{ m.title }}</a></td>
            <td>{{ m.get_format_display|default:"" }}</td>
            <td>{{ m.get_type_display|default:"" }}</td>
            <td>{{ m.target_group.all|join:", " }}</td>
        </tr>

    {% endfor %}
    </tdbody>
 <table>

agit_material/templates/agit_material/blocks/_pictures.html
<ul>
    {% for p in pictures %}
        <li>
            <img src="{{ p.image.url }}" title="{{ p.title }}" height=140 />
        </li>
    {% endfor %}
</ul>

agit_material/templates/agit_material/pagination.html
{% if paginator.num_pages > 1 %}
	<ul class="pagination">
		{% if page_obj.has_previous %}
		    <li><a href="?{{ query_string }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
		{% else %}
			<li class="disabled"><span>&laquo;</span></li>
		{% endif %}
	
	
		{% for n in paginator.page_range %}
			{% if n == page_obj.number %}
				<li class="active"><span>{{ n }}</li>
			{% else %}
				<li><a href="?{{ query_string }}&page={{ n }}">{{ n }}</a></li>
			{% endif %}
		{% endfor %}
	
	
		{% if page_obj.has_next %}
		    <li><a href="?{{ query_string }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
		{% else %}
			<li class="disabled"><span>&raquo;</span></li>
		{% endif %}
	
	</ul>
{% endif %}

agit_material/templates/agit_material/search.html
{% extends 'agit_material/base.html' %}



{% block content %}

    <form action="" method="get">
        {# csrf_token #}
        {{ form.as_p }}
        <input type="submit" value="Поиск">
    </form>

    <br>
    {% include 'agit_material/blocks/_atigmaterial_list.html' %}
    <br>
    Всего {{ paginator.count }}<br>
    {% include "agit_material/pagination.html" %}

    <br><br>
    Картинки по вашему запросу:
    {% include 'agit_material/blocks/_pictures.html' %}
    <a href="">поиск по картинкам</a>

{% endblock %}